-- Layer rule for the grid, for ~/.config/hypr/looknfeel.lua.
--
-- NO BLUR HERE. The plugin blurs the wallpaper itself, in QML, because it
-- needs a radius it can animate from nothing up to full over the length of the
-- opening -- and a compositor blur is a property of the layer, on or off, with
-- no half of it. Asking for both would be paying twice for the same pixels,
-- and the surface ends up opaque anyway, so there is nothing behind it left to
-- see. `ignore_alpha` has nothing to govern either.
--
-- `no_anim` / `animation = "none"`: the plugin animates its own entrance and
-- exit. Omarchy otherwise fades every layer surface in over 400ms and out over
-- 150ms, which multiplies into the fade the plugin is already applying, and on
-- the way out only STARTS once the surface unmaps -- after the plugin has
-- finished fading it to nothing. Both keys are needed: `animation` picks the
-- style, `no_anim` is what Hyprland checks for layer surfaces.
hl.layer_rule({ match = { namespace = "launchpad" }, no_anim = true, animation = "none" })
